//try catch are used to handle exceptions.
//The code which seems to give error is kept in try block.
//catch block includes statement to execute if error occurs in try block

public class CWH_trycatch {
    public static void main(String[] args) {
        int a=5000;
        int b=0;
        try{
            int c=a/b;
            System.out.println("The result is "+c);
        }
        catch(Exception e){
            System.out.println("We failed to divide.Reason ");
            System.out.println(e);
        }
    }
}
